version: "3.9"
services:
  server:
    build: ./
    container_name: diplom
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/app
      spring.jpa.hibernate.ddl-auto: create-drop
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql